### ISSUE TITLE
App never exits

### ISSUE THREAD

**Issue by brw** [achingbrain/nat-port-mapper#73]
It seems like that when using the (in my case UPnP) client the app will never exit because `discovery.stop()` is never called after it's [started](https://github.com/achingbrain/nat-port-mapper/blob/310f48cf68ff9b78dbd767217e4668314ba9c566/src/discovery/index.ts#L85). I wasn't sure if `discovery.stop()` could be placed right after the gateway has been discovered or if it should placed separately and only called on `client.close()`. Or if this should be necessary at all even.

**Comment by achingbrain** [comment]
Fixed in #77 - discovery is now stopped after finding a gateway, please give it a go!
