### ISSUE TITLE
Wrong gateway with second router as access point

### ISSUE THREAD

**Issue by brw** [achingbrain/nat-port-mapper#74]
In my network I'm generally connected to a router that functions as an access point for another network. It seems like this router is generally (but not always) the first to come up when nat-port-mapper tries to discover the gateway, whereas it should actually use the other router instead.

I don't know much about how UPnP and NAT-PMP work or how they're supposed to work (or about networking in general honestly), but it seems like other apps on my system utilizing UPnP generally do manage to find the correct gateway to use, or they just send requests to both.

I didn't set my network up this way, nor do I have much control over it. Maybe I can just disable UPnP on that AP router but I'm also thinking about users who might not know as much about these things and have similarly weird setups. Better defaults are always nice to have.

Just wondering if you have any thoughts on this.

**Comment by brw** [comment]
Yea that would probably work. When it comes to the apps I'm using I can see that Syncthing and Resilio Sync have opened ports through UPnP on both routers, so they do send UPnP requests to all devices reporting as a gateway.

TailScale however manages to correctly only use the WAN-connected router. It seems to do this by attempting to [discover the system's gateway IP](https://github.com/tailscale/tailscale/blob/8e5cfbe4ab11713e383b3ff0d978f116320de2a3/net/netmon/state.go#L556) first and using that for UPnP requests. But that's quite a bit more involved of course.

**Comment by achingbrain** [comment]
You can now either use [findGateways](https://achingbrain.github.io/nat-port-mapper/interfaces/UPnPNAT.html#findGateways) to perform a SSDP search for all internet gateway devices on your network, or [getGateway](https://achingbrain.github.io/nat-port-mapper/interfaces/UPnPNAT.html#getGateway) if you know the location of the XML descriptor ahead of time.
